Donald-Chow/smartvacay

- Gemfile
- Gemfile.lock
- app/policies/application_policy.rb
- app/policies/itinerary_policy.rb
- app/policies/location_policy.rb
- app/policies/trip_policy.rb
- test/policies/itinerary_policy_test.rb
- test/policies/location_policy_test.rb
- test/policies/trip_policy_test.rb
added gem pundit,
run bundle install
created policies for locations, trip and itinerary
> added pundit

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_general.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/trips_controller.rb
- app/models/trip.rb
- app/policies/trip_policy.rb
- app/views/pages/home.html.erb
Created the basic HTML for the home page
Will need to work on the background blur and form input for date
> Home Page V1

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_general.scss
- app/assets/stylesheets/components/_header.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_navbar.html.erb
added nav. bar and title bar (header) components
added google fonts
> add nav-bar and title-bar

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/locations_controller.rb
- app/models/favorite.rb
- app/models/location.rb
- app/models/user.rb
- app/policies/favorite_policy.rb
- app/policies/location_policy.rb
- app/views/layouts/application.html.erb
- app/views/locations/index.html.erb
- app/views/locations/my_favorites.html.erb
- config/initializers/acts_as_favoritor.rb
- config/routes.rb
- db/migrate/20230523055425_acts_as_favoritor_migration.rb
- db/schema.rb
- db/seeds.rb
- test/policies/favorite_policy_test.rb
Did the location#index, get bookmarks to work and display location#my_favorites
> Feature suggested locations

- Gemfile.lock
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_general.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_locations.scss
- app/controllers/trips_controller.rb
- app/views/layouts/application.html.erb
- app/views/locations/index.html.erb
- app/views/locations/show.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_navbar.html.erb
fixed navbar
blur the background image of Hero in homepage
add some link
> Modify homepage

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_navbar.scss
- app/controllers/trips_controller.rb
- app/policies/trip_policy.rb
- app/services/trip_generator.rb
- app/views/trips/generate.html.erb
- config/routes.rb
- db/seeds.rb
Magic Button ProtoType MAY be working. Need more testing
> Magic button

- app/assets/stylesheets/config/_fonts.scss
- app/controllers/trips_controller.rb
- app/models/user.rb
- app/views/itineraries/index.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- app/views/trips/show.html.erb
Make it so that One user can only have ONE trip
Trip page is empty with a button if no itinerary
Show itinerary if there is Itinerary
> Only one trip

- app/views/itineraries/index.html.erb
Added if statement for icon and check if location is restaurant
> icon changes dynamically if it is a restaurant

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_locationShow.scss
- app/javascript/controllers/flatpickr_controller.js
- app/views/locations/show.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_carousel.html.erb
- app/views/shared/_navbar.html.erb
- package.json
- yarn.lock
added carousel on location (show) page
fixed some css layout
> Fix datepickr

- app/views/itineraries/index.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
Fixed issue where if user is not signed in, page break because the link doesn't work
> Login homepage

- app/javascript/controllers/index.js
- app/javascript/controllers/itin_collapse_controller.js
- app/views/itineraries/index.html.erb
Added collapsible itin per date
> click to collapse works

- app/javascript/controllers/google_search_controller.js
- app/views/locations/index.html.erb
added a search result in locations view
> Search view

- app/assets/stylesheets/application.scss
- app/views/locations/index.html.erb
> Merge issue

- app/assets/stylesheets/application.scss
- app/controllers/locations_controller.rb
- app/views/locations/my_favorites.html.erb
I refactored my code in the "locations#my_favorites" as well as the view page(locations/my_favorites) without changing the css.  Hopefully this will be more readable and modifiable in the future in case of changes.
> Refactored

- app/assets/stylesheets/components/_card.scss
- app/views/locations/index.html.erb
Created cards for the grid view in Location Index
> grid view for location

- app/javascript/controllers/google_search_controller.js
changed locationBias: '10000', (size of tokyo)
included   if (results[i].photos) {
> changed locationBias, included   if (results[i].photos)

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_general.scss
- app/assets/stylesheets/locations/_index.scss
- app/assets/stylesheets/pages/_locations.scss
- app/views/locations/index.html.erb
- db/seeds.rb
- Modified search bar location
- Modified card design and make sure text doesn't exceed the card
- Used random pictures
> Modified css of location index

- app/controllers/locations_controller.rb
- app/javascript/controllers/google_search_controller.js
- app/services/google_places.rb
- app/views/locations/_location_card.html.erb
- app/views/locations/index.html.erb
Search is perform with Service.rb
Query passed to backend with params
return page with results
consider new JS to be run
cards location out of place
> Search in controller

- app/controllers/locations_controller.rb
- app/models/location.rb
- app/services/google_places.rb
- app/views/locations/_location_card.html.erb
Now we can search and add location to the database
> able to create new location in database

- app/controllers/locations_controller.rb
- app/views/locations/index.html.erb
Now main location page have top locations
> Now we have top locations

- app/views/locations/index.html.erb
> View for Location Index should be fixed

- app/views/shared/_navbar.html.erb
fixed empty user cannot see page issue
> fixed nav bar

- app/assets/stylesheets/application.scss
> un uncommenet fltpicker

- app/controllers/locations_controller.rb
> changed find method

- app/controllers/locations_controller.rb
copy and pasted caused a typo. fixed
> fixed typo for search

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_locations.scss
- app/views/locations/my_favorites.html.erb
modified:   app/assets/stylesheets/components/_card.scss
modified:   app/assets/stylesheets/pages/_locations.scss
modified:   app/views/locations/my_favorites.html.erb
> centralized locations page cards

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_general.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/locations/_index.scss
- app/assets/stylesheets/pages/_locations.scss
- app/views/locations/index.html.erb
- app/views/locations/show.html.erb
- app/views/pages/home.html.erb
- db/seeds.rb
- Modified font types
- Unified "Search results" and "Top locations" headline by applying the same font color, text shadow, etc
- Changed the description in the homepage (Yin is now working on the homepage picture.  We want to put the description inside the picture later)
- Cards inside "card locations" now display in the center
> CSS changes

- app/controllers/locations_controller.rb
- app/views/locations/_location_card.html.erb
- app/views/shared/_carousel.html.erb
No location have multiple pictures
> now instance have multiple pictures

- app/controllers/locations_controller.rb
- app/services/google_places.rb
> limiting to only 4 pics

- app/assets/stylesheets/components/_alert.scss
Alert is now above the nav bar
> Move up alert

- app/views/itineraries/index.html.erb
> Hide itin draft

- app/views/locations/my_favorites.html.erb
> added empty query

- app/views/locations/my_favorites.html.erb
> testing without icon

- app/views/locations/my_favorites.html.erb
> make icon unsplash

- config/environments/production.rb
Debugging and testing why URL redirect fail
> removed force SSL to test

- app/assets/stylesheets/components/_general.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_locations.scss
- app/javascript/controllers/flatpickr_controller.js
- app/views/locations/index.html.erb
- app/views/pages/home.html.erb
- change back the nav bar color
> Searchbar color

- app/assets/stylesheets/components/_general.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_locations.scss
- app/assets/stylesheets/pages/_trips.scss
- app/controllers/locations_controller.rb
- app/javascript/controllers/active_tab_controller.js
- app/javascript/controllers/index.js
- app/views/itineraries/index.html.erb
- app/views/locations/_location_card.html.erb
- app/views/locations/index.html.erb
- app/views/locations/my_favorites.html.erb
- app/views/locations/show.html.erb
- app/views/shared/_navbar.html.erb
- app/views/trips/generate.html.erb
- app/views/trips/show.html.erb
- changed nav-bar have active tab
- fixed "bottom margin" problems on all pages
- fixed overflow-x on fav. list page
- changed bookmark color to orange
> Active navbar

- app/controllers/locations_controller.rb
- app/controllers/user_reviews_controller.rb
- app/models/location.rb
- app/models/user_review.rb
- app/policies/user_review_policy.rb
- app/views/locations/show.html.erb
- app/views/user_reviews/new.html.erb
- config/routes.rb
- db/migrate/20230529013802_create_user_reviews.rb
- db/schema.rb
- test/controllers/user_reviews_controller_test.rb
- test/models/user_review_test.rb
- test/policies/user_review_policy_test.rb
modified:   app/controllers/locations_controller.rb
new file:   app/controllers/user_reviews_controller.rb
modified:   app/models/location.rb
new file:   app/models/user_review.rb
new file:   app/policies/user_review_policy.rb
modified:   app/views/locations/show.html.erb
new file:   app/views/user_reviews/new.html.erb
modified:   config/routes.rb
new file:   db/migrate/20230529013802_create_user_reviews.rb
modified:   db/schema.rb
new file:   test/controllers/user_reviews_controller_test.rb
new file:   test/models/user_review_test.rb
new file:   test/policies/user_review_policy_test.rb
> added User  Reviews

- app/assets/stylesheets/components/_general.scss
- app/controllers/locations_controller.rb
- app/controllers/trips_controller.rb
- app/models/search.rb
- app/services/google_places.rb
- app/views/itineraries/index.html.erb
- app/views/locations/index.html.erb
- config/initializers/smtp.rb
Bug #1 
email wont sent
fixed typo
Bug #2 
Trip wont create
issue was with creating top attractions
Typo fixed
Bug #3 
Transit direction not showing
Issue was with query
Fixed query prompt
Bug #4 
All pages clipped by header
Fixed CSS
Features #1 
Added Top Shopping on the explore page
Load time google query increased becareful!
> Debugging wednesday

- app/mailers/user_mailer.rb
- app/models/trip.rb
- app/models/user.rb
- app/views/user_mailer/trip.html.erb
- app/views/user_mailer/welcome.html.erb
- config/initializers/smtp.rb
Also removed email to user upon sign-up
> Trip mailer - sending email to users upon trip creation

- app/controllers/itineraries_controller.rb
- app/controllers/trips_controller.rb
- app/javascript/controllers/sortable_controller.js
fixed sort issue and route render issue
> Itin sort issue

- app/controllers/locations_controller.rb
- app/models/location.rb
change recomendation logic and location phone issue
> Better recommendation

- app/assets/stylesheets/components/_avatar.scss
- app/views/locations/_filtered_list.html.erb
- app/views/locations/_location_card.html.erb
- app/views/locations/my_favorites.html.erb
modified:   app/assets/stylesheets/components/_avatar.scss
modified:   app/views/locations/_filtered_list.html.erb
modified:   app/views/locations/_location_card.html.erb
modified:   app/views/locations/my_favorites.html.erb
> My favorites - changed cards

- app/views/locations/_filtered_list.html.erb
For some reason some code has been repeated on my favs.  Fixed it.
> Fixed broken code

- app/views/locations/show.html.erb
- just changed the width of map on show location page to 330px
> changed the map width to 330px
